### ISSUE TITLE
Ticketron

### ISSUE THREAD

**Issue by RumbleFrog** [MaxDBNET/MaxDB#1]
## A custom ticket plugin that has way more features and up to date.

A more elegant approach through a ticket system.

### Todo:

- [x] Priority system (~~Permission Core~~, Group Membership, Donor)
- [x] Menu Building
- [x] Notification System (Both in-game and SBC)
- [x] ~~Connect Shop Natives~~
- [x] ~~SBC UI~~
- [x] Admin Ability to reply to ticket ~~(Doesn't have to be self-handled)~~
- [x] Admin ability to self-assign ticket
- [x] Admin ability to close ticket
- [x] ~~Admin ability to mark/tag ticket~~
- [x] ~~Admin ability to take credits if ticket is marked as abuse [Requires Shop]~~
- [x] User ability to view all tickets created by them
- [x] User ability to reply to their ticket
- [x] User ability to close their own ticket
- [x] Ability to tag player
- [x] Ingame notification (BoolTrue = Shown)
- [x] Optional Natives

### Command Table:

- [x] !TicketQueue #
- [x] !Handle
- [x] !Unhandle
- [x] ~~!TagTicket~~
- [x] !CloseTicket
- [x] !ReplyTicket
- [x] !TagPlayer
- [x] !MyTickets #
- [x] !ViewTicket
- [x] !Ticket
- [x] !MyQueue #

**Comment by RumbleFrog** [comment]
Done.
